CREATE SEQUENCE common_seq START WITH 100000;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    login      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    role       VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX users_unique_login_idx ON users (login);

