CREATE TABLE scan_source
(
    id       INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    code     VARCHAR(255) NOT NULL,
    url      VARCHAR(255) NOT NULL,
    icon_url VARCHAR(255) NOT NULL
);

INSERT INTO scan_source(id, code, url, icon_url)
VALUES (1, 'hh_ru', 'https://hh.ru/', 'https://hh.ru/favicon.ico'),
       (2, 'habr_com', 'https://career.habr.com/', 'https://career.habr.com/images/favicons/favicon-16.png'),
       (3, 'sql_ru', 'https://www.sql.ru/', 'https://www.sql.ru/favicon.ico');

CREATE TABLE task
(
    id             INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    keyword        VARCHAR(255)         NOT NULL,
    city           VARCHAR(255),
    scan_limit     TIMESTAMP            NOT NULL,
    active         BOOLEAN DEFAULT true NOT NULL,
    next_launch    TIMESTAMP,
    repeat_rule    VARCHAR(255)         NOT NULL,
    scan_source_id INTEGER              NOT NULL REFERENCES scan_source (id),
    amount         INTEGER DEFAULT 0    NOT NULL,
    user_id        INTEGER              NOT NULL REFERENCES users (id) ON DELETE CASCADE
);