DROP TABLE post IF EXISTS;
DROP TABLE users IF EXISTS;

DROP TABLE car IF EXISTS;

DROP TABLE vendor IF EXISTS;
DROP TABLE body IF EXISTS;
DROP TABLE engine IF EXISTS;
DROP TABLE transmission IF EXISTS;

DROP SEQUENCE common_seq IF EXISTS;

CREATE SEQUENCE common_seq START WITH 100000;

CREATE TABLE body
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE engine
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE transmission
(
    id   INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);

CREATE TABLE vendor
(
    id        INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    country   VARCHAR(255) NOT NULL,
    logo_link VARCHAR(255)
);

CREATE UNIQUE INDEX body_unique_type_idx ON body (type);

CREATE UNIQUE INDEX engine_unique_type_idx ON engine (type);

CREATE UNIQUE INDEX transmission_unique_type_idx ON transmission (type);

CREATE UNIQUE INDEX vendor_unique_name_idx ON vendor (name);

CREATE TABLE car
(
    id              INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    vendor_id       INTEGER           NOT NULL REFERENCES vendor (id),
    model           VARCHAR(255)      NOT NULL,
    year            INTEGER           NOT NULL,
    mileage         INTEGER DEFAULT 0 NOT NULL,
    transmission_id INTEGER           NOT NULL REFERENCES transmission (id),
    engine_id       INTEGER           NOT NULL REFERENCES engine (id),
    body_id         INTEGER           NOT NULL REFERENCES body (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    name       VARCHAR(255)            NOT NULL,
    login      VARCHAR(255)            NOT NULL,
    password   VARCHAR(255)            NOT NULL,
    registered TIMESTAMP DEFAULT now() NOT NULL,
    role       VARCHAR(255)            NOT NULL,
    enabled    BOOLEAN   DEFAULT true  NOT NULL
);

CREATE UNIQUE INDEX users_unique_login_idx ON users (login);

CREATE TABLE post
(
    id        INTEGER GENERATED BY DEFAULT AS SEQUENCE common_seq PRIMARY KEY,
    title     VARCHAR(255)            NOT NULL,
    message   VARCHAR(2000),
    posted    TIMESTAMP DEFAULT now() NOT NULL,
    price     INTEGER,
    car_id    INTEGER                 REFERENCES car (id) ON DELETE SET NULL,
    user_id   INTEGER                 NOT NULL REFERENCES users (id) ON DELETE CASCADE
);